In [2]:
import numpy as np

In [4]:
# Q.1 Creat 4X2 Array
a=np.array([[1,2],[3,4],[5,6],[7,8]])
print(f"array:{a}")
print(f"Shape of an array: {a.shape}")
print(f"array dimension:{a.ndim}")

array:[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape of an array: (4, 2)
array dimension:2


In [5]:
#Q.2 Create a 5X2 integer array from a range between 100 to 200such that the difference between each element is 10
a=np.arange(100,200,10).reshape((5,2))
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [14]:
# Q.3 return array of the column in the third column from all rows
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(f'Third column from all rows ; {a[0:,2:]}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Third column from all rows ; [[3]
 [6]
 [9]]


In [29]:
# Q.4  return array of odd rows and even columns
a=np.arange(3,61,3).reshape((5,4))
print(a)
a[::2,1::2]

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]


array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [ ]:
#Q.5 return array of odd rows and even columns


In [28]:
#Q.5 Split the array into four equal-sized sub-arrays
a=np.arange(10,34,1).reshape((8,3))
print(a)
np.split(a,4)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [33]:
# Q.6 Create an 8x8 matrix and fill it with a checkerboard pattern.

a = np.ones((3,3))
print("Checkerboard pattern:")
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
